FROM python:3.11.6-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.frontend.txt .
RUN pip install --no-cache-dir -r requirements.frontend.txt

COPY . .

EXPOSE 8502

CMD ["streamlit", "run", "frontend/admin_app.py", "--server.port=8502", "--server.address=0.0.0.0"]